- name: Generate SSH key with passphrase and set permissions
  hosts: localhost
  connection: local
  vars:
    ssh_key_filepath: "{{ ssh_key_filepath }}"
    ssh_passphrase: "{{ ssh_passphrase }}"
  tasks:
    - name: Generate SSH key "{{ ssh_key_filepath }}"
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_filepath }}"
        type: rsa
        size: 4096
        passphrase: "{{ ssh_passphrase }}"
        state: present
        force: no
        private_key_format: ssh

    - name: Set permissions for private key
      file:
        path: "{{ ssh_key_filepath }}"
        mode: '400'

    - name: Set permissions for public key
      file:
        path: "{{ ssh_key_filepath }}.pub"
        mode: '600'
        
    - name: Convert private key to PEM format
      shell:
        openssl rsa -in "{{ ssh_key_filepath }}" -out "{{ ssh_key_filepath }}.pem" -passin pass:{{ ssh_passphrase }}
      args:
        warn: false

    - name: Set permissions for PEM Private key
      file:
        path: "{{ ssh_key_filepath }}.pem"
        mode: '400'
