- name: Generate SSH key with passphrase and set permissions
  hosts: localhost
  connection: local
  vars:
    ssh_key_filepath: "{{ ssh_key_filepath }}"
    ssh_passphrase: "{{ ssh_passphrase }}"
  tasks:
    - name: Generate SSH key "{{ ssh_key_filepath }}"
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_filepath }}"
        type: rsa
        size: 4096
        passphrase: "{{ ssh_passphrase }}"
        state: present
        force: no

    - name: Set permissions for private key
      file:
        path: "{{ ssh_key_filepath }}"
        mode: '400'

    - name: Set permissions for public key
      file:
        path: "{{ ssh_key_filepath }}.pub"
        mode: '600'
