---
- name: Generate SSH key with passphrase and set permissions
  hosts: localhost
  connection: local
  vars:
    ssh_key_filepath: "{{ ssh_key_filepath }}"
    ssh_passphrase: "{{ ssh_passphrase }}"
  tasks:
    - name: Generate SSH key "{{ ssh_key_filepath }}"
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_filepath }}"
        type: rsa
        size: 4096
        passphrase: "{{ ssh_passphrase }}"
        state: present
        force: no
        private_key_format: ssh

    - name: Set permissions for private key
      file:
        path: "{{ ssh_key_filepath }}"
        mode: '0400'

    - name: Set permissions for public key
      file:
        path: "{{ ssh_key_filepath }}.pub"
        mode: '0600'
        
    - name: Convert private key to PEM format using ssh-keygen
      command: >
        ssh-keygen -p -m PEM -f "{{ ssh_key_filepath }}" -N "{{ ssh_passphrase }}"

    - name: Set permissions for PEM private key
      file:
        path: "{{ ssh_key_filepath }}"
        mode: '0400'
