---
- name: Generate SSH key with passphrase and set permissions
  hosts: localhost
  connection: local
  vars:
    ssh_key_filepath: "/home/ec2-user/test"
    ssh_passphrase: "Orange1sn3wb1aCk"
  tasks:
    - name: Generate private key
      community.crypto.openssl_privatekey:
        path: "{{ ssh_key_filepath }}"
        type: rsa
        size: 4096
        passphrase: "{{ ssh_passphrase }}"
        state: present
        force: no
      register: private_key

    - name: Generate public key
      community.crypto.openssl_publickey:
        path: "{{ ssh_key_filepath }}"
        privatekey_path: "{{ ssh_key_filepath }}"
        passphrase: "{{ ssh_passphrase }}"
        state: present
        force: no
      when: private_key.changed
      
